---
title: "Quarto Basics"
#author: 
format: html
editor: source
toc: true
toc-location: left
#theme: 
self-contained: true

---



Some basic things to know about creating an HTML Quarto doc! 


1.) Go ahead and add # followed by some text then ## followed by some more text (hint: This will become a header).  






Hit the "Render" button above.

2.) One the sentence below place this ** in front and after the words "bold text." Now do this again but to the words "italic text" but with only one star on each end.  





Hit the "Render" button above.


3.) Head to the YAML at the top and enter your name author section. (Hint: be sure to remove the # in front of the word)





Hit the "Render" button above.  


4.) Add the word "sketchy" to the end of theme in the YAML. (Hint: don't include the " "). 




Hit the "Render" button above.


5.) Copy and paste this [ ](https://quarto.org/docs/output-formats/html-themes.html) and enter the word "Click Here" in between the [ ] (hint: don't include the " ").






6.) Copy and paste the following equation e = mc^2 below, now put $ in front and after it. 





7.) Head to the top right corner of your screen and click the +c button that is next to the ⬆️ arrow. 






8.) Within the code chunk enter 1+1 and press the green play button in the upper right corner of the chunk.





**Bonus:** *(Only for 'The Last of Us' fans 🙃)*


```{r}
#| warning: false
#| messages: false

if (!require("devtools")) install.packages("devtools") # installs devtools if you don't have it

library(devtools)  

devtools::install_github("nvietto/nopunintended") 

library(nopunintended)

nopunintended()


```

